/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0            (GUI_ID_USER + 0x00)
#define ID_TEXT_0            (GUI_ID_USER + 0x01)
#define ID_TEXT_1            (GUI_ID_USER + 0x02)
#define ID_TEXT_2            (GUI_ID_USER + 0x03)
#define ID_SPINBOX_0            (GUI_ID_USER + 0x04)
#define ID_BUTTON_0            (GUI_ID_USER + 0x05)
#define ID_BUTTON_1            (GUI_ID_USER + 0x06)
#define ID_BUTTON_2            (GUI_ID_USER + 0x07)
#define ID_BUTTON_3            (GUI_ID_USER + 0x08)
#define ID_BUTTON_4            (GUI_ID_USER + 0x09)
#define ID_BUTTON_5            (GUI_ID_USER + 0x0A)
#define ID_DROPDOWN_0            (GUI_ID_USER + 0x0B)
#define ID_DROPDOWN_1            (GUI_ID_USER + 0x0C)
#define ID_DROPDOWN_2            (GUI_ID_USER + 0x0D)
#define ID_BUTTON_6            (GUI_ID_USER + 0x0E)
#define ID_DROPDOWN_3            (GUI_ID_USER + 0x0F)
#define ID_DROPDOWN_4            (GUI_ID_USER + 0x10)
#define ID_TEXT_3            (GUI_ID_USER + 0x12)
#define ID_TEXT_4            (GUI_ID_USER + 0x13)
#define ID_TEXT_5            (GUI_ID_USER + 0x14)
#define ID_TEXT_6            (GUI_ID_USER + 0x15)
#define ID_TEXT_7            (GUI_ID_USER + 0x16)
#define ID_BUTTON_7            (GUI_ID_USER + 0x17)
#define ID_BUTTON_8            (GUI_ID_USER + 0x18)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 72, 480, 200, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 1, 35, 100, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 1, 101, 100, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 0, 146, 100, 30, 0, 0x64, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_0, 104, 26, 100, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 101, 97, 100, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 220, 96, 100, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 341, 97, 100, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 100, 145, 100, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 220, 145, 100, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 342, 145, 100, 30, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 302, 22, 45, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_1, 359, 22, 45, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_2, 420, 22, 45, 18, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Range", ID_BUTTON_6, 238, 65, 50, 20, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_3, 316, 65, 45, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_4, 393, 65, 45, 18, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Hour", ID_TEXT_3, 313, 4, 34, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Min", ID_TEXT_4, 375, 4, 28, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Sec", ID_TEXT_5, 433, 4, 39, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Low", ID_TEXT_6, 329, 47, 33, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "High", ID_TEXT_7, 405, 47, 34, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "On", ID_BUTTON_7, 238, 7, 50, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Off", ID_BUTTON_8, 238, 35, 50, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
SPINBOX_Handle hdata;
DROPDOWN_Handle hour,min,sec,tem_low,tem_high;
int Temperature_now=26;
int speed_mode=2;//0=HIGH ,1=MIDDLE,2=LOW
int mode_mode=2;// 0=COLD,1=WARM,2=WIND
int alarm_hour,alarm_min,alarm_sec=0;
int set_tem_low,set_tem_high=0;
int lcd_state=2;
int flag_low,flag_high,close_flag_range=0;
extern int on_flag;
extern int close_flag;
extern void Open_Alarm(void);
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "Tempature");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000000FF));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "Speed");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF0000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "Mode");
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00008000));
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "High");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, "Middle");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetText(hItem, "Low");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetText(hItem, "Cold");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetText(hItem, "Warm");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetText(hItem, "Wind");
    // USER START (Optionally insert additional code for further widget initialization)
    hdata = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
    SPINBOX_SetValue(hdata,26);
    SPINBOX_SetRange(hdata,18,30);
    
    hour = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_SetAutoScroll(hour,0);
    DROPDOWN_SetListHeight(hour,60);
    DROPDOWN_AddString(hour,"0");
    DROPDOWN_AddString(hour,"1");
    DROPDOWN_AddString(hour,"2");
    DROPDOWN_AddString(hour,"3");
    
    
    min = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
    DROPDOWN_SetAutoScroll(min,0);
    DROPDOWN_SetListHeight(min,60);
    DROPDOWN_AddString(min,"0");
    DROPDOWN_AddString(min,"1");
    DROPDOWN_AddString(min,"2");
    DROPDOWN_AddString(min,"3");
    
    sec = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_2);
    DROPDOWN_SetAutoScroll(sec,0);
    DROPDOWN_SetListHeight(sec,60);
    DROPDOWN_AddString(sec,"0");
    DROPDOWN_AddString(sec,"1");
    DROPDOWN_AddString(sec,"2");
    DROPDOWN_AddString(sec,"3");
    
    tem_low = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_3);
    DROPDOWN_SetAutoScroll(tem_low,0);
    DROPDOWN_SetListHeight(tem_low,60);
    DROPDOWN_AddString(tem_low,"21");
    DROPDOWN_AddString(tem_low,"22");
    DROPDOWN_AddString(tem_low,"23");
    DROPDOWN_AddString(tem_low,"24");
    
    tem_high = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_4);
    DROPDOWN_SetAutoScroll(tem_high,0);
    DROPDOWN_SetListHeight(tem_high,60);
    DROPDOWN_AddString(tem_high,"25");
    DROPDOWN_AddString(tem_high,"26");
    DROPDOWN_AddString(tem_high,"27");
    DROPDOWN_AddString(tem_high,"28");

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_SPINBOX_0: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        Temperature_now=SPINBOX_GetValue(hdata);

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        speed_mode=0;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        speed_mode=1;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        speed_mode=2;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        mode_mode=0;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        mode_mode=1;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        mode_mode=2;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_0: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_1: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        
       
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_2: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'Range'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        close_flag_range=1;
        flag_low=DROPDOWN_GetSel(tem_low);
        if(flag_low==0)
        {
          set_tem_low=21;
        }
        if(flag_low==1)
        {
          set_tem_low=22;
        }
        if(flag_low==2)
        {
          set_tem_low=23;
        }
        if(flag_low==3)
        {
          set_tem_low=24;
        }
        
        flag_high=DROPDOWN_GetSel(tem_high);
        if(flag_high==0)
        {
          set_tem_high=25;
        }
        if(flag_high==1)
        {
          set_tem_high=26;
        }
        if(flag_high==2)
        {
          set_tem_high=27;
        }
         if(flag_high==3)
        {
          set_tem_high=28;
        }
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_3: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
        
      // USER END
      }
      break;
    case ID_DROPDOWN_4: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
       
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'On'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        alarm_hour=DROPDOWN_GetSel(hour);
        alarm_min=DROPDOWN_GetSel(min);
        alarm_sec=DROPDOWN_GetSel(sec);
        lcd_state=0;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)

      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by 'Off'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        alarm_hour=DROPDOWN_GetSel(hour);
        alarm_min=DROPDOWN_GetSel(min);
        alarm_sec=DROPDOWN_GetSel(sec);
        lcd_state=1;
        Open_Alarm();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
